version: "3.0"
services:
  check_version:
    image: golang:latest
    volumes:
      - .:/src
    command: go version
  init:
    image: golang:latest
    volumes:
      - .:/src
    command: go mod init github.com/streamwest-1629/rehearsal
  tidy:
    image: golang:latest
    volumes:
      - .:/src
    command: go mod tidy
  build:
    image: golang:latest
    volumes:
      - .:/src
    command: go build
