version: "3.0"
services:
  check_version:
    image: golang:latest
    volumes:
      - .:/src
    command: go version
  init:
    image: golang:latest
    volumes:
      - .:/src
    entrypoint: /src/scripts/init.sh
  tidy:
    image: golang:latest
    volumes:
      - .:/src
    entrypoint: /src/scripts/tidy.sh
  build:
    image: golang:latest
    volumes:
      - .:/src
    entrypoint: /src/scripts/build.sh
