version: "3.0"
services:
  check_version:
    build:
      context: .
      dockerfile: devcontainer.Dockerfile
    volumes:
      - .:/src
    command: go version
  init:
    build:
      context: .
      dockerfile: devcontainer.Dockerfile
    volumes:
      - .:/src
    entrypoint: /src/scripts/init.sh
  tidy:
    build:
      context: .
      dockerfile: devcontainer.Dockerfile
    volumes:
      - .:/src
    entrypoint: /src/scripts/tidy.sh
  build:
    build:
      context: .
      dockerfile: devcontainer.Dockerfile
    volumes:
      - .:/src
    entrypoint: /src/scripts/build.sh
